### ISSUE TITLE
Problem with downloading all ebooks.

### ISSUE THREAD

**Issue by Tokariew** [luk6xff/Packt-Publishing-Free-Learning#105]
It looks like packt, added page layout in my ebooks page. Because of it, script runned with -da option download only first subpage -- 10 ebooks.

**Comment by mjenczmyk** [comment]
Yes, the list of user's books is being paginated now. I'll try to make a pull request to make the script work again (although I'll appreciate that if somebody will be faster than me).

**Comment by mjenczmyk** [comment]
https://github.com/igbt6/Packt-Publishing-Free-Learning/pull/108/
