### ISSUE TITLE
Drop support for Python 2.7.x

### ISSUE THREAD

**Issue by mjenczmyk** [luk6xff/Packt-Publishing-Free-Learning#118]
Hi,

support for Python 2 had to be dropped in 2015, but its end of life was postponed five years and it won't be supported since 2020. There are more and more packages dropping support for Python 2 nowdays, maybe we could also support only Python 3.x versions?

I could make a pull request removing support for Python 2.

**Comment by igbt6** [comment]
Yep, good idea :)

**Comment by mjenczmyk** [comment]
Resolved in #111.
