### ISSUE TITLE
too many values to unpack (expected 1)

### ISSUE THREAD

**Issue by StinThiago** [luk6xff/Packt-Publishing-Free-Learning#122]
Hi All! Today I got this issue. Does anyone have any idea of what is causing this?
Follow print!
Many thanks in advance.

![image](https://user-images.githubusercontent.com/17601585/53230560-3fc6f880-3687-11e9-8cc2-c54e4e38bf86.png)

**Comment by mjenczmyk** [comment]
It's because according to Packt's API there are not one, but two Packt Free Learning offers (you can see that in developer's console when opening Free Learning website). I'll modify the script to grab all available offers and add it to #121 pull request.

**Comment by develsites** [comment]
@mjenczmyk I've cloned your changes but I have a new issue `ImportError: No module named 'api'`

<img width="1289" alt="screen shot 2019-02-24 at 07 14 27" src="https://user-images.githubusercontent.com/2625408/53292826-9d348400-3804-11e9-8ea0-7ea644b25588.png">

**Comment by mjenczmyk** [comment]
@develsites I'm sorry, I messed it up - thanks for noticing. For now install it using `pip install git+https://github.com/mjenczmyk/Packt-Publishing-Free-Learning.git@api-fix` command, I'll make a pull request in the evening.

The main problem from the issue seems to be temporarily resolved as now there is only on Packt Free Learning Book, we may choose to assume that such problem will or won't happen again.

**Comment by develsites** [comment]
@mjenczmyk thank you for fixing but I have another one problem after uploading files `[ERROR] - Exception occurred Incorrect file paths argument format`

<img width="1351" alt="screen shot 2019-02-26 at 16 51 56" src="https://user-images.githubusercontent.com/2625408/53399519-20153480-39e7-11e9-9caf-de0a536ec806.png">

**Comment by mjenczmyk** [comment]
@develsites Thanks, you found another problem - it happens if you try to upload to GoogleDrive. I'll take care of it as soon as I'll find the time (I cannot promise anything before next Tuesday).

**Comment by develsites** [comment]
@mjenczmyk Thank you :) 

What's about this? 

`[INFO] - There is no books with provided titles: ['Fundamentals of Malware Analysis [Video]'] at your account!`

<img width="1680" alt="screen shot 2019-02-28 at 14 12 23" src="https://user-images.githubusercontent.com/2625408/53545009-f84adb80-3b62-11e9-87d5-1b90e3837d49.png">

**Comment by laurentlemercier** [comment]
Hello @mjenczmyk 
Exception raised line 334 : google_drive.send_files(paths). Looks like the file paths are not correct.
I was wondering if the statements from line 317 to 322
ebook.download_books(api_client, into_folder=into_folder)
should be changed to something like : 
ebook.download_books(api_client, into_folder=cfg.download_folder_path)
Hope this helps, regards
Laurent

**Comment by luk6xff** [comment]
@develsites  @laurentlemercier I fixed the problem at 10ee7186d1c23e15b3eab1197eed8cd4b0d29fef
Please take a look, in case of any problems please open another ticket. I am closing this one.

**Comment by mjenczmyk** [comment]
Thanks, I'll release a new patch version.
