### ISSUE TITLE
Download videos also?

### ISSUE THREAD

**Issue by greggmarshall** [luk6xff/Packt-Publishing-Free-Learning#137]
Now that the free learning is including videos, it would be really nice if the script could download the videos, especially since it appears the API is the only way to access free learning assets other than on-line.

Would this be hard to add?

**Comment by mjenczmyk** [comment]
Should be easy. Try installing script via `pip install git+https://github.com/mjenczmyk/Packt-Publishing-Free-Learning.git@id` and add `video` file type to your config file, see if that works as expected.

**Comment by greggmarshall** [comment]
You are right it was easy to add the video format and have it downloaded.  Still running but I wonder what a .video file format actually is?

**Comment by mjenczmyk** [comment]
That's right - it's a zip file. You can see it in line 201 in modified file. Does it work for you?

**Comment by greggmarshall** [comment]
Like a champ.  I can also confirm you have resolved the timeout issue completely.  It has been running about 5 or 6 hours, it's picking up a number of videos I bought during one of the $5 sales....

**Comment by mjenczmyk** [comment]
Glad I could help ;) I've already merged it so you can install the script using the usual command `pip install git+https://github.com/luk6xff/Packt-Publishing-Free-Learning.git@master --upgrade` - there is also a pull request in case we decide we want the package on PyPi to simplify the command further.
