### ISSUE TITLE
Packt Video

### ISSUE THREAD

**Issue by ranrinc** [luk6xff/Packt-Publishing-Free-Learning#138]
Its seems that Packt is now release video, can we download this too?

**Comment by mjenczmyk** [comment]
Yup, look at the latest (yesterday's) release.

**Comment by AlessioC** [comment]
I'm not sure wether you have already fixed it in the last couple hours, but yesterday I saw that when I included a video_tag in download_formats, the script first downloaded the code as "name_of_book_video.zip" and subsequently the videos folder with the same file name, thus making the video download fail

**Comment by ranrinc** [comment]
Is there away for me to download previous miss download?

**Comment by mjenczmyk** [comment]
You're right, there are conflicting file names. What I'd do is to skip downloading code files for videos as they are already in the package with the video. Does it seem reasonable to you or maybe you have another idea how to solve this problem?

@ranrinc Just remove code files and download and run download again with proposed fix installed (you can install it with `pip install git+https://github.com/mjenczmyk/Packt-Publishing-Free-Learning.git@code --upgrade`). 

You can see the pull request here: #141.

**Comment by ranrinc** [comment]
@mjenczmyk alright.. I got this part and yes its now function correctly. Thanks

**Comment by mjenczmyk** [comment]
Should we merge? Is this the fix you would expect? What do you think @ranrinc @AlessioC?

**Comment by ranrinc** [comment]
@mjenczmyk I have no objection on merging this..

**Comment by AlessioC** [comment]
@mjenczmyk Another possibility could be to force the video and code download separately (therefore not together) but I don't know if is possible. Otherwise yes, I think that your fix is a good loophole. :)
