### ISSUE TITLE
Op "-da -f" not working anymore

### ISSUE THREAD

**Issue by SR-G** [luk6xff/Packt-Publishing-Free-Learning#143]
It was working fine before around 2019/02/27 (i would say) but not anymore.
I'm willing to download all ebooks, and to have a subfolder created for each book.

The `-da -f` seemed fine for that and was working fine, but nowadays i get : 

```
Error: -f option requires an argument
```

(whereas `-f`` should not require any argument, i would say)

I have (re)installed packt-cli with `pip install packt --upgrade` today, same behavior.

**Comment by mjenczmyk** [comment]
`pip install git+https://github.com/mjenczmyk/Packt-Publishing-Free-Learning.git@f --upgrade` Does it help?

**Comment by SR-G** [comment]
Indeed, i can confirm this one is working.

```
[INFO] - JWT token has been fetched successfully!
[INFO] - Getting your books data...
[INFO] - Books data has been successfully fetched.
[INFO] - Title: "Enterprise Automation with Python [Video]"
[INFO] - Downloading code for ebook: "Enterprise Automation with Python [Video]"...
[SUCCESS] - Code for ebook "Enterprise Automation with Python [Video]" downloaded successfully!
[INFO] - Title: "Mastering Blockchain"
(...)
```
