### ISSUE TITLE
packt-cli --help shows, that -f needs a parameter, but doesn't seem to have a meaning

### ISSUE THREAD

**Issue by dennisdenk** [luk6xff/Packt-Publishing-Free-Learning#145]
![grafik](https://user-images.githubusercontent.com/19978270/54885442-5924b580-4e7c-11e9-8816-20c008f200ee.png)
packt-cli --help shows, that -f needs a parameter, but doesn't seem to have a meaning

**Comment by mjenczmyk** [comment]
It has been fixed in version 1.2.2, but thanks for noticing ;)
