### ISSUE TITLE
DOWNLOAD_DATA section mandatory

### ISSUE THREAD

**Issue by Mte90** [luk6xff/Packt-Publishing-Free-Learning#147]
If I want only to claim on my profile it is not possible.
Right now I configured that the download path is `/tmp`

**Comment by mjenczmyk** [comment]
We could move download path and download formats to CLI parameters (the configuration file is too bulky right now anyway) - but I wouldn't like to do this without @luk6xff consent. What both of you think about that?

**Comment by Mte90** [comment]
Well I don't need to download it so maybe add as not mandatory to use the tool will require a bit of refactoring.

**Comment by mjenczmyk** [comment]
Could you see if #160 resolves your problem? Just install script with `pip install git+https://github.com/mjenczmyk/Packt-Publishing-Free-Learning.git@downloader` and see if it works for you.

**Comment by Mte90** [comment]
![Screenshot_20190701_113147](https://user-images.githubusercontent.com/403283/60425943-e140f680-9bf3-11e9-98bc-ec4f67d50806.png)
I am getting this error

**Comment by mjenczmyk** [comment]
Thanks, that's on me. I've fixed this and updated the branch, it should work now.

**Comment by Mte90** [comment]
it works :-)

**Comment by mjenczmyk** [comment]
Awesome, have you checked that you can also download products without AntiCaptcha settings? If so, I'd be able to merge then.
