### ISSUE TITLE
Crontab error

### ISSUE THREAD

**Issue by ranrinc** [luk6xff/Packt-Publishing-Free-Learning#156]
When I run crontab it encounters this error:

```
Traceback (most recent call last):
  File "/home/ranrinc/Packt/venv/bin/packt-cli", line 10, in <module>
    sys.exit(packt_cli())
  File "/home/ranrinc/Packt/venv/lib/python3.6/site-packages/click/core.py", li$
    return self.main(*args, **kwargs)
  File "/home/ranrinc/Packt/venv/lib/python3.6/site-packages/click/core.py", li$
    _verify_python3_env()
  File "/home/ranrinc/Packt/venv/lib/python3.6/site-packages/click/_unicodefun.$
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configure$

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```
However, it runs fine when I execute the CLI using my user's login. So crontab running but produce this error..

**Comment by mjenczmyk** [comment]
[This](https://stackoverflow.com/questions/32234393/encoding-issue-with-python3-and-click-package) seems to describe a similar problem as you seem to struggle with. You will find there some ideas on how to resolve this.

Anyway, is setting your locales to - let's say - `en_US.UTF-8` an option?

**Comment by mjenczmyk** [comment]
I'm closing the issue - it's not a problem with a script itself and it's been a long time since last message was posted.
