### ISSUE TITLE
Exception occurred expected string or bytes-like object

### ISSUE THREAD

**Issue by somhi** [luk6xff/Packt-Publishing-Free-Learning#157]
$ packt-cli -g
[INFO] - JWT token has been fetched successfully!
[INFO] - Start grabbing ebook...
[ERROR] - Exception occurred expected string or bytes-like object

Any ideas on this error I got the last two days ?

I'm on Ubuntu 18.04

**Comment by ad-m** [comment]
What version of Python?

**Comment by somhi** [comment]
Python 2.7.15rc1

**Comment by ad-m** [comment]
That vesion of Python is not supported ( https://github.com/luk6xff/Packt-Publishing-Free-Learning/blob/master/setup.py#L45-L47 ).

**Comment by mjenczmyk** [comment]
That's true, I'll close the issue.

**Comment by somhi** [comment]
$ python3 --version
Python 3.6.7

I also have python v3.   The thing is the app has worked for more than two months, and a few days ago it started showing that error.

**Comment by somhi** [comment]
Well now it's working again.  
Just for the record I solved reinstalling again the sofware with:  
pip3 install packt --upgrade

Cheers
