### ISSUE TITLE
Cannot grab the book

### ISSUE THREAD

**Issue by vulgur** [luk6xff/Packt-Publishing-Free-Learning#158]
Cannot grab the free book, alway got the error as below.
 > [ERROR] - Exception occurred Error ERROR_KEY_DOES_NOT_EXIST occured: Account authorization key not found in the system

Downloading is working well if the book was already grabbed on the website.

**Comment by mjenczmyk** [comment]
It seems that your AntiCaptcha API key is not valid (as I could guess from the message you provided). I didn't have any problems recently. Could you make sure your API key is valid?

**Comment by vulgur** [comment]
Yes, API key is missing in the config file.
