### ISSUE TITLE
Available download formats

### ISSUE THREAD

**Issue by mjenczmyk** [luk6xff/Packt-Publishing-Free-Learning#163]
It's been a while since Packt doesnt provide other formats than html (kinda bookdown). My question is that this script allows downloading books in this format too?

Thanks

_Originally posted by @danmaxis in https://github.com/luk6xff/Packt-Publishing-Free-Learning/issues/162#issuecomment-521267024_

**Comment by mjenczmyk** [comment]
I'm not sure if I understood well what you meant (I could either think that you're asking about downloading HTML format or other formats).

Anyway, with the script you can download Packt products from Free Learning offer in PDF, EPUB  and MOBI formats (in case it's a e-book) or ZIP (in case it's a video). Regardless of whether it's e-book or video you can also download ZIP file with code samples (they are already in ZIP package with video files).

Nowadays you can only download code samples from the website for books claimed in Free Learning offer, but Packt haven't secured their API so script can download other files anyway - it's not intended for the user to be able to download them.

Feel free to ask if something is not clear.

**Comment by danmaxis** [comment]
Oh sorry, I wasnt specific. I was referring about daily Free Learning material (books or videos) that demand clicking on "Claim Now" button. 
These material are added to "My Owned Products" section but only with "Open in Reader" button available. I was wondering if the script could download those books too.

**Comment by mjenczmyk** [comment]
Yes, you can download every available format, as if you've bought the book.

**Comment by mjenczmyk** [comment]
@danmaxis I see @luk6xff has closed the issue, feel free to reopen or ask more if you have any more questions.
