### ISSUE TITLE
Script now failing to fetch JWT token or download, change to website?

### ISSUE THREAD

**Issue by eharris** [luk6xff/Packt-Publishing-Free-Learning#169]
Starting Nov 18, for `packt-cli -gd` the script has started producing:
```
[ERROR] - Fetching JWT token failed!
[INFO] - Start grabbing ebook...
[ERROR] - Exception occurred 'NoneType' object is not iterable
```

Nothing has changed with login credentials or any other config, and it was working fine prior to 11/18.  Using version 1.4.3.

**Comment by mjenczmyk** [comment]
The script no longer works for me either. It seems that they require ReCaptcha solution for login request now (not only for Free Learning claim request), they've also rewritten their website to be rendered by AngularJS (but I'm not sure when they did this, it may have happened when they introduced API).

I'll try try to fix this (i cannot promise any deadline, it may be today, end of week or two weeks), you can try to do it independently if you want - you may be faster.

Thanks for submitting the issue, I haven't configured e-mails, so currently I don't get notifications about script errors.

**Comment by mjenczmyk** [comment]
It seems that I've got a solution. Try installing script with `pip install git+https://github.com/luk6xff/Packt-Publishing-Free-Learning.git@recaptcha-on-login`, see if that works.

I'll have to clean up this code further (than I'll make a pull request), I currently solve ReCaptcha twice - I think we can do this only once.

**Comment by mjenczmyk** [comment]
All right, but have you installed the script with the command I provided? If not can you describe what have you done and from where to where have you copied the files (and what are you trying to achieve)?

**Comment by puzzledvacuum** [comment]
I can confirm installing the script with `pip install git+https://github.com/luk6xff/Packt-Publishing-Free-Learning.git@recaptcha-on-login` works.

**Comment by jackyhjj** [comment]
Hi, it seems that we are not able to own the daily free ebook from the website now, is there any other way to download it ?

**Comment by jackyhjj** [comment]
Please help 

<img width="871" alt="Screen Shot 2019-11-20 at 14 13 27" src="https://user-images.githubusercontent.com/7055599/69216939-f832b600-0b9f-11ea-950a-f2edd736b1c9.png">

**Comment by mjenczmyk** [comment]
@jackyhjj You're using Python 2.7, the script doesn't support anything less than Python 3.5.

**Comment by mjenczmyk** [comment]
I'm still not convinced that it works, and I've got a single shot a day (ReCaptcha solution seems to be mandatory iff user tries to claim a book he doesn't already have) - today I got 400 response when claiming book.

```
{'message': 'The recaptcha solution is missing.', 'errorCode': 3000043, 'errorId': '85cbbf1e-e636-4cfb-afee-a057dc138395'}
```

I'll update the code afternoon, but I won't merge it before tomorrow.
I'll update the script once more, but I'll need another day to make su

**Comment by jackyhjj** [comment]
> @jackyhjj You're using Python 2.7, the script doesn't support anything less than Python 3.5.

I have checked my brew version of python is 3.7.5 but when i run packt-cli it keeps going to 2.7 Is there any setting or parameter that i can manually override using python3 ?

**Comment by Danielx303** [comment]
For now - it is working for me!

What have I done? 
1. I have made a new copy of this packt script. 
2. I use "github desktop" program to download the latest branch of this script. 
3. Install it from "setup.py" file, restart my PC and... it works!!

**Comment by jackyhjj** [comment]
Is there anyway to download the ebook based on the bookID ? if yes, what parameter should I use ?

**Comment by laurentlemercier** [comment]
On a raspberry pi , rasbian, I have made a new virtual env python and downloaded this version. It works perfectly.

@ mjenczmyk : thanks a lot !!!!

**Comment by mjenczmyk** [comment]
I've merged, let me know if something will be wrong. Today I'll release a 1.5.0 version.

**Comment by fref** [comment]
Do we need a recaptcha token to fetch books?

**Comment by mjenczmyk** [comment]
Yes, you need it since the beginning of the year. Since this week you need it to log into Packt account.

**Comment by fref** [comment]
Isn't there any way to do this recaptcha manually? I just want to download the books.

**Comment by eharris** [comment]
@fref See #172 for a request for a way to solve recaptcha manually.

**Comment by jackyhjj** [comment]
@mjenczmyk saw your commit 6 hours ago, and in the config file there is a 'key' field. What to be filled in the key field ?

**Comment by mjenczmyk** [comment]
It's the [Anti Captcha](https://anti-captcha.com/) API key, you'd need to register there to obtain one.

**Comment by greggmarshall** [comment]
Is there a way to get less than $10 of credits on the Anti Captcha site other than the probably too few demo credits?
