### ISSUE TITLE
login to packt issue

### ISSUE THREAD

**Issue by alfiqmiq** [luk6xff/Packt-Publishing-Free-Learning#174]
from a few days...

packt-cli -gd
[ERROR] - Fetching JWT token failed!
[INFO] - Start grabbing ebook...
[ERROR] - Exception occurred 'NoneType' object is not iterable

as i think is new packt double check issue (config for connection is ok)

![image](https://user-images.githubusercontent.com/9507245/69334637-786a2180-0c5b-11ea-8021-c471226c8934.png)

**Comment by mjenczmyk** [comment]
Isn't that duplicate of #169?

**Comment by mjenczmyk** [comment]
I'm assuming it is - in other case we can reopen the issue.
