### ISSUE TITLE
Incorrectly names files with special characters

### ISSUE THREAD

**Issue by RiaanvWyk** [luk6xff/Packt-Publishing-Free-Learning#179]
Hi there,
the folders and files created from book titles containing special characters such as "# or +" are not correctly named. For example "Learn C# in 7 days" is saved as "Learn C in 7 days" and "The Modern C++ Challenge" is saved as "The Modern C Challenge"

**Comment by mjenczmyk** [comment]
We are using [`python-slugify`](https://github.com/un33k/python-slugify) to convert book title to file name. According to [StackOverflow](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) the characters you are writing about are valid file name characters.

We may whitelist # and + characters so they won't be removed by `python-slugify`. Any more characters to whitelist?

**Comment by RiaanvWyk** [comment]
Excellent, thanks for the prompt reply! I also concluded that it was the python-slugify package and started playing around with the source. It would be great if you could whitelist # and +. It would be nice if the period character ".", "-" and "–" is also whitelisted (if that isn't asking too much). Some of the books contain them e.g. "C# 7.1 and .NET Core 2.0 – Modern Cross-Platform Development"

**Comment by RiaanvWyk** [comment]
Actually I forked the repository and just removed the use of slugify to keep the full filename as it is returned from Packtpub. Since it is a personal preference I don't think it is needed to make these changes on the main branch so I'm closing the ticket!

**Comment by mjenczmyk** [comment]
@RiaanvWyk Please, have a look at #180 - does it look OK?

**Comment by RiaanvWyk** [comment]
@mjenczmyk Looks good, thanks!

**Comment by mjenczmyk** [comment]
I'll merge it and release a new patch version. Thanks for issuing this bug, I wasn't aware of it.

**Comment by greggmarshall** [comment]
Amusing side effect of the change.  When I did a monthly download of claimed books, it is downloading some older titles that now have different filenames with the additional characters.  Hardly an issue, just an observation.

**Comment by mjenczmyk** [comment]
Makes sense, previously file names could easily conflict with each other.
