### ISSUE TITLE
Question about download Video

### ISSUE THREAD

**Issue by Danielx303** [luk6xff/Packt-Publishing-Free-Learning#188]
C:\ZZZZ\Packt-Publishing-Free-Learning-master>packt-cli -gd
[INFO] - Started solving ReCAPTCHA for https://www.packtpub.com/ website...
[INFO] - Waiting for completion of the 212279712 task...
[SUCCESS] - Solution found for 212279712 task.
[INFO] - JWT token has been fetched successfully!
[INFO] - Start grabbing ebook...
[INFO] - Getting your books data...
[INFO] - Books data has been successfully fetched.
[INFO] - A new Packt Free Learning ebook "Ethical Hacking for Beginners [Video]" has been grabbed!
[INFO] - Title: "Ethical Hacking for Beginners [Video]"
[INFO] - Downloading "Ethical Hacking for Beginners [Video]" video...
[ERROR] - Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
[INFO] - 0 ebooks have been downloaded!
[SUCCESS] - Good, looks like all went well! :-)

C:\ZZZZ\Packt-Publishing-Free-Learning-master>pause
Press any key to continue . . .

Why this task doesn't download video from packt? 

In my configFile.cfg I have like this:

[DOWNLOAD_DATA]
download_folder_path: D:\me
download_formats: pdf, video, code

**Comment by mjenczmyk** [comment]
I recall something like that happening before 1.4.2 version of the script, are you using the fresh version? Could you check what's the version of the script you're running (`pip freeze | grep packt` on Debian derived GNU/Linux system)?

**Comment by Danielx303** [comment]
Yes, you're right!

I have two different catalogues with a script on my PC. One is the newest, I'm upgrading him using the program "GitHub for desktop", and the second catalogue - I'm abandoned this because I had a problem with it.

And - first - it is 1.5.1
second - 1.4.2 :)

I thought that I really abandoned this second one, but I've checked one more time my "schtasks.exe" and my "*.bat" file and.. My 'bat' task was in the first-good catalogue, but it using the script from the second catalogue.

It was my mistake. Your answer contributed to the repair of the script on my PC - Thank you for it! :-)

**Comment by mjenczmyk** [comment]
Glad I could help ;)
