### ISSUE TITLE
Exception occurred too many values to unpack (expected 1)

### ISSUE THREAD

**Issue by plaidshirtakos** [luk6xff/Packt-Publishing-Free-Learning#194]
Script is unable to get daily ebook. I got following error during execution of `packt-cli -gd`

```
[INFO] - JWT token has been fetched successfully!
[INFO] - Start grabbing ebook...
[ERROR] - Exception occurred too many values to unpack (expected 1)
```

**Comment by laurentlemercier** [comment]
Hello
Are you sure version 1.5.3 is installed ? I have made this [modification ](https://github.com/luk6xff/Packt-Publishing-Free-Learning/commit/2f1e19d0329ef9dac2c546a56d5ebf9a8d5c3188) to handle this case, it works correctly (on raspbian).
Regards
Laurent
