### ISSUE TITLE
File placed wrongly with pip

### ISSUE THREAD

**Issue by Mte90** [luk6xff/Packt-Publishing-Free-Learning#198]
![immagine](https://user-images.githubusercontent.com/403283/90633599-9c788480-e226-11ea-8cc2-ad003ca0b6cc.png)
This is how the files are placed after installing it with pip. 
The files are in the dist-packages root and not in a specific folder.

**Comment by mjenczmyk** [comment]
Why isn't that OK? Can you provide link to the documentation describing how it should be done? I'm not saying it's OK though, it should be fixed if there is something wrong with it.

**Comment by Mte90** [comment]
that files should be created inside a folder and not put in the root as it is now.

**Comment by mjenczmyk** [comment]
Can you see if #199 looks right? Now installed files should be placed in the `packt` directory. You can install the script with `pip install git+https://github.com/luk6xff/Packt-Publishing-Free-Learning.git@packaging` command.

I've tried do make sure everything works fine, but double-check it - I wouldn't like to rely on myself.

**Comment by Mte90** [comment]
to me seems everything fine :-)
