### ISSUE TITLE
Do we still need bat script when there is PowerShell?

### ISSUE THREAD

**Issue by mjenczmyk** [luk6xff/Packt-Publishing-Free-Learning#99]
Is the bat script still needed? As for now all supported Windows systems allow useds to use PowerShell, so maybe this bat script is obsolete and may be removed? I'm assuming that script usage on Windows does not differ from usage on Debian (with the exception of cron tasks on Debian vs schtasks on Windows). 

Sorry if I'm writing something that is false; I don't use Windows anymore - in that case correct me.

**Comment by igbt6** [comment]
Actually we can remove it ;), It was once done for my friend and it somehow still exist in the repo :)

**Comment by mjenczmyk** [comment]
OK, I'll make a pull request than - do you happen to have access to machine with Windows? I'll remove the file and update `README.md` but I'll need to have it checked that my changes won't break anything.

**Comment by igbt6** [comment]
yup, i can test it, feel free to open a PR, thx!

**Comment by mjenczmyk** [comment]
https://github.com/igbt6/Packt-Publishing-Free-Learning/pull/100

**Comment by mjenczmyk** [comment]
Made obsolete by #111.
